/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package persewaan_mobil;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.concurrent.TimeUnit;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JAG
 */
public class app_rental extends javax.swing.JFrame {

    DefaultTableModel model;
    datamobil objmobil = new datamobil();
    Object [] data = new Object[4];
    persewaan objsewa = new persewaan();
    /**
     * Creates new form app_rental
     */
    public app_rental() {
        initComponents();
        setLocationRelativeTo(this);
        model = (DefaultTableModel)tabelSewa.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        namaPelanggan = new javax.swing.JTextField();
        noHP = new javax.swing.JTextField();
        noKTP = new javax.swing.JTextField();
        noTransaksi = new javax.swing.JTextField();
        uangMuka = new javax.swing.JTextField();
        biayaTambahan = new javax.swing.JTextField();
        totalTagihan = new javax.swing.JTextField();
        BTNperiksa = new javax.swing.JButton();
        BTNtampil = new javax.swing.JButton();
        tglTransaksi = new javax.swing.JTextField();
        tglPinjam = new javax.swing.JTextField();
        tglKembali = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        namaMobil = new javax.swing.JTextField();
        IDmobil = new javax.swing.JTextField();
        jenisMobil = new javax.swing.JTextField();
        Tarif = new javax.swing.JTextField();
        BTNtambah = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelSewa = new javax.swing.JTable();
        BTNkeluar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TXTpreview = new javax.swing.JTextArea();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(8, 32, 50));
        jPanel1.setForeground(new java.awt.Color(8, 32, 50));
        jPanel1.setToolTipText("");

        jLabel1.setBackground(new java.awt.Color(207, 245, 231));
        jLabel1.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(207, 245, 231));
        jLabel1.setText("APLIKASI RENTAL MOBIL");

        jTabbedPane1.setBackground(new java.awt.Color(13, 76, 146));
        jTabbedPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        jTabbedPane1.setForeground(new java.awt.Color(13, 76, 146));

        jPanel2.setBackground(new java.awt.Color(0, 18, 51));

        jPanel4.setBackground(new java.awt.Color(44, 57, 75));
        jPanel4.setForeground(new java.awt.Color(44, 57, 75));

        jLabel2.setBackground(new java.awt.Color(207, 245, 231));
        jLabel2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(207, 245, 231));
        jLabel2.setText("No. Transaksi");

        jLabel3.setBackground(new java.awt.Color(207, 245, 231));
        jLabel3.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(207, 245, 231));
        jLabel3.setText("Tgl. Transaksi");

        jLabel4.setBackground(new java.awt.Color(207, 245, 231));
        jLabel4.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(207, 245, 231));
        jLabel4.setText("No. KTP");

        jLabel5.setBackground(new java.awt.Color(207, 245, 231));
        jLabel5.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(207, 245, 231));
        jLabel5.setText("No. HP");

        jLabel6.setBackground(new java.awt.Color(207, 245, 231));
        jLabel6.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(207, 245, 231));
        jLabel6.setText("Nama Pelanggan");
        jLabel6.setToolTipText("");

        jLabel7.setBackground(new java.awt.Color(207, 245, 231));
        jLabel7.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(207, 245, 231));
        jLabel7.setText("Tgl. Pinjam");

        jLabel8.setBackground(new java.awt.Color(207, 245, 231));
        jLabel8.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(207, 245, 231));
        jLabel8.setText("Tgl. Kembali");

        jLabel9.setBackground(new java.awt.Color(207, 245, 231));
        jLabel9.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(207, 245, 231));
        jLabel9.setText("Uang Muka");

        jLabel10.setBackground(new java.awt.Color(207, 245, 231));
        jLabel10.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(207, 245, 231));
        jLabel10.setText("Biaya Tambahan");

        jLabel11.setBackground(new java.awt.Color(207, 245, 231));
        jLabel11.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(207, 245, 231));
        jLabel11.setText("TOTAL TAGIHAN");

        namaPelanggan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                namaPelangganKeyTyped(evt);
            }
        });

        noHP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                noHPKeyTyped(evt);
            }
        });

        noKTP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                noKTPKeyTyped(evt);
            }
        });

        noTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noTransaksiActionPerformed(evt);
            }
        });
        noTransaksi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                noTransaksiKeyTyped(evt);
            }
        });

        uangMuka.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                uangMukaKeyTyped(evt);
            }
        });

        biayaTambahan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                biayaTambahanKeyTyped(evt);
            }
        });

        totalTagihan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalTagihanActionPerformed(evt);
            }
        });

        BTNperiksa.setText("Periksa");
        BTNperiksa.setToolTipText("");
        BTNperiksa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNperiksaActionPerformed(evt);
            }
        });

        BTNtampil.setText("Tampil");
        BTNtampil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNtampilActionPerformed(evt);
            }
        });

        tglTransaksi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tglTransaksiKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(BTNperiksa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BTNtampil))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(totalTagihan, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                        .addComponent(biayaTambahan)
                        .addComponent(uangMuka)
                        .addComponent(noTransaksi)
                        .addComponent(noKTP)
                        .addComponent(noHP)
                        .addComponent(namaPelanggan))
                    .addComponent(tglTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tglPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tglKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(noTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tglTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(noKTP, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(noHP, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(namaPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tglPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tglKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(uangMuka, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(biayaTambahan, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(totalTagihan, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNperiksa)
                    .addComponent(BTNtampil))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(51, 71, 86));
        jPanel5.setForeground(new java.awt.Color(51, 71, 86));

        jLabel12.setBackground(new java.awt.Color(207, 245, 231));
        jLabel12.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(207, 245, 231));
        jLabel12.setText("ID Mobil");

        jLabel13.setBackground(new java.awt.Color(207, 245, 231));
        jLabel13.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(207, 245, 231));
        jLabel13.setText("Nama Mobil");

        jLabel14.setBackground(new java.awt.Color(207, 245, 231));
        jLabel14.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(207, 245, 231));
        jLabel14.setText("Jenis Mobil");

        jLabel15.setBackground(new java.awt.Color(207, 245, 231));
        jLabel15.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(207, 245, 231));
        jLabel15.setText("Tarif");

        IDmobil.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                IDmobilKeyTyped(evt);
            }
        });

        Tarif.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TarifKeyTyped(evt);
            }
        });

        BTNtambah.setText("Tambah");
        BTNtambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNtambahActionPerformed(evt);
            }
        });

        tabelSewa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Mobil", "Nama Mobil", "Jenis Mobil", "Tarif"
            }
        ));
        jScrollPane1.setViewportView(tabelSewa);

        BTNkeluar.setText("KELUAR");
        BTNkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNkeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BTNkeluar)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(namaMobil, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(IDmobil, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jenisMobil, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Tarif, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BTNtambah))
                                .addGap(30, 30, 30)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(IDmobil, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(namaMobil, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jenisMobil, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(Tarif, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(BTNtambah)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(BTNkeluar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("FORM", jPanel2);

        jPanel3.setBackground(new java.awt.Color(0, 18, 51));

        TXTpreview.setColumns(20);
        TXTpreview.setRows(5);
        jScrollPane2.setViewportView(TXTpreview);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("PREVIEW", jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void totalTagihanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalTagihanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalTagihanActionPerformed

    private void noTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noTransaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noTransaksiActionPerformed

    private void BTNkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNkeluarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BTNkeluarActionPerformed

    private void BTNperiksaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNperiksaActionPerformed
        String notransaksi= noTransaksi.getText();
        String tgltransaksi= tglTransaksi.getText();
        String noktp= noKTP.getText();
        String nohp= noHP.getText();
        String namapelanggan= namaPelanggan.getText();
        String tglpinjam= tglPinjam.getText();
        String tglkembali= tglKembali.getText();
        long uangmuka= Long.valueOf(uangMuka.getText());
        long biayatambahan= Long.valueOf(biayaTambahan.getText());
        
        objsewa.setdatasewa(notransaksi, tgltransaksi, noktp, nohp, namapelanggan,
                tglpinjam, tglkembali, uangmuka, biayatambahan);
        TXTpreview.setText("");
        
        DateFormat date = new SimpleDateFormat("dd-mm-yyy");
        
        try
        {
            Date tglawal= date.parse(tglpinjam);
            Date tglakhir= date.parse(tglkembali);
            
            int lama= (int)TimeUnit.MILLISECONDS.toDays(tglakhir.getTime()-tglawal.getTime());
            if (lama<0)
            {
                JOptionPane.showMessageDialog(null, "Tanggal Salah!");
            } else
            {
                int total=0;
                for (int i = 0; i < tabelSewa.getRowCount(); i++)
                {
                    int tarif=Integer.parseInt((String)tabelSewa.getValueAt(i, 3));
                    total= total+(tarif*lama);
                }
                int totalakhir=(int) (total+biayatambahan-uangmuka);
                totalTagihan.setText(""+totalakhir);
            }
        } catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "Tanggal tidak sesuai format !");
        }
        
    }//GEN-LAST:event_BTNperiksaActionPerformed

    private void BTNtambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNtambahActionPerformed
        
        long idmobil = Long.parseLong(IDmobil.getText());
        String namamobil = namaMobil.getText();
        String jenismobil = jenisMobil.getText();
        long tarif = Long.parseLong(Tarif.getText());

        objmobil.setdatamobil(idmobil, namamobil, jenismobil, tarif);
        data[0]= String.valueOf(objmobil.getId_mobil());
        data[1]= objmobil.getNamaMobil();
        data[2]= objmobil.getJenisMobil();
        data[3]= String.valueOf(objmobil.getTarif());
        model.addRow(data);
        clear();
                
    }//GEN-LAST:event_BTNtambahActionPerformed

    private void BTNtampilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNtampilActionPerformed
        if (totalTagihan.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Masukkan transaksi lebih dahulu !");
        } else
        {
            TXTpreview.append("-------------------------------------------------------------------------------------");
            TXTpreview.append("\n");
            TXTpreview.append("REKAPITULASI TRANSAKSI RENTAL MOBIL \n");
            TXTpreview.append("-------------------------------------------------------------------------------------");
            TXTpreview.append("\n");
            TXTpreview.append("\n");
            TXTpreview.append("\n");
            TXTpreview.append("No. Transaksi  : \t"+objsewa.getNoTransaksi()+"\n");
            TXTpreview.append("Tanggal Transaksi  : \t"+objsewa.getTgl_Transaksi()+"\n");
            TXTpreview.append("-------------------------------------------------------------------------------------");
            TXTpreview.append("\n");
            TXTpreview.append("Nama Pelanggan  : \t"+objsewa.getNamaPelanggan()+"\n");
            TXTpreview.append("No. KTP  : \t\t"+objsewa.getNoKTP()+"\n");
            TXTpreview.append("No. HP  : \t\t"+objsewa.getNoHP()+"\n");
            TXTpreview.append("-------------------------------------------------------------------------------------");
            TXTpreview.append("\n");
            TXTpreview.append("Tanggal Pinjam  : \t"+objsewa.getTgl_pinjam()+"\n");
            TXTpreview.append("Tanggal Kembali  : \t"+objsewa.getTgl_kembali()+"\n");
            TXTpreview.append("Uang Muka  : \t\t"+objsewa.getUang_muka()+"\n");
            TXTpreview.append("-------------------------------------------------------------------------------------");
            TXTpreview.append("\n");
            TXTpreview.append("\n");
            TXTpreview.append("DATA PEMINJAMAN MOBIL \n");
            TXTpreview.append("-------------------------------------------------------------------------------------");
            TXTpreview.append("\n");
            TXTpreview.append("ID Mobil\tNama Mobil\tJenis Mobil\tTarif \n");
            TXTpreview.append("-------------------------------------------------------------------------------------");
            TXTpreview.append("\n");
            for (int i = 0; i < tabelSewa.getRowCount(); i++)
            {
                String a= (String)tabelSewa.getValueAt(i, 0)+"\t"
                        +(String)tabelSewa.getValueAt(i, 1)+"\t"
                        +(String)tabelSewa.getValueAt(i, 2)+"\t"
                        +(String)tabelSewa.getValueAt(i, 3)+"\t";
                TXTpreview.append(a);
                TXTpreview.append("\n");
            }
            TXTpreview.append("\n");
            TXTpreview.append("-------------------------------------------------------------------------------------");
            TXTpreview.append("\n");
            TXTpreview.append("Uang Muka  : \t\t"+objsewa.getUang_muka()+"\n");
            TXTpreview.append("TOTAL TAGIHAN  : \t"+totalTagihan.getText()+"\n");
            TXTpreview.append("-------------------------------------------------------------------------------------");
            jTabbedPane1.setSelectedIndex(1);
            
        }
    }//GEN-LAST:event_BTNtampilActionPerformed

    private void noTransaksiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_noTransaksiKeyTyped
        if (Character.isAlphabetic(evt.getKeyChar()))
        {
            JOptionPane.showMessageDialog(null, "Harus angka!");
            evt.consume();
        }
    }//GEN-LAST:event_noTransaksiKeyTyped

    private void tglTransaksiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tglTransaksiKeyTyped
        if (Character.isAlphabetic(evt.getKeyChar()))
        {
            JOptionPane.showMessageDialog(null, "Harus angka!");
            evt.consume();
        }
    }//GEN-LAST:event_tglTransaksiKeyTyped

    private void noKTPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_noKTPKeyTyped
        if (Character.isAlphabetic(evt.getKeyChar()))
        {
            JOptionPane.showMessageDialog(null, "Harus angka!");
            evt.consume();
        }
    }//GEN-LAST:event_noKTPKeyTyped

    private void noHPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_noHPKeyTyped
        if (Character.isAlphabetic(evt.getKeyChar()))
        {
            JOptionPane.showMessageDialog(null, "Harus angka!");
            evt.consume();
        }
    }//GEN-LAST:event_noHPKeyTyped

    private void uangMukaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_uangMukaKeyTyped
        if (Character.isAlphabetic(evt.getKeyChar()))
        {
            JOptionPane.showMessageDialog(null, "Harus angka!");
            evt.consume();
        }
    }//GEN-LAST:event_uangMukaKeyTyped

    private void biayaTambahanKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_biayaTambahanKeyTyped
        if (Character.isAlphabetic(evt.getKeyChar()))
        {
            JOptionPane.showMessageDialog(null, "Harus angka!");
            evt.consume();
        }
    }//GEN-LAST:event_biayaTambahanKeyTyped

    private void IDmobilKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IDmobilKeyTyped
        if (Character.isAlphabetic(evt.getKeyChar()))
        {
            JOptionPane.showMessageDialog(null, "Harus angka!");
            evt.consume();
        }
    }//GEN-LAST:event_IDmobilKeyTyped

    private void TarifKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TarifKeyTyped
        if (Character.isAlphabetic(evt.getKeyChar()))
        {
            JOptionPane.showMessageDialog(null, "Harus angka!");
            evt.consume();
        }
    }//GEN-LAST:event_TarifKeyTyped

    private void namaPelangganKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_namaPelangganKeyTyped
        if (!Character.isAlphabetic(evt.getKeyChar()))
        {
            JOptionPane.showMessageDialog(null, "Harus huruf!");
            evt.consume();
        }
    }//GEN-LAST:event_namaPelangganKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(app_rental.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(app_rental.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(app_rental.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(app_rental.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new app_rental().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNkeluar;
    private javax.swing.JButton BTNperiksa;
    private javax.swing.JButton BTNtambah;
    private javax.swing.JButton BTNtampil;
    private javax.swing.JTextField IDmobil;
    private javax.swing.JTextArea TXTpreview;
    private javax.swing.JTextField Tarif;
    private javax.swing.JTextField biayaTambahan;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jenisMobil;
    private javax.swing.JTextField namaMobil;
    private javax.swing.JTextField namaPelanggan;
    private javax.swing.JTextField noHP;
    private javax.swing.JTextField noKTP;
    private javax.swing.JTextField noTransaksi;
    private javax.swing.JTable tabelSewa;
    private javax.swing.JTextField tglKembali;
    private javax.swing.JTextField tglPinjam;
    private javax.swing.JTextField tglTransaksi;
    private javax.swing.JTextField totalTagihan;
    private javax.swing.JTextField uangMuka;
    // End of variables declaration//GEN-END:variables

    private void clear() {
        IDmobil.setText("");
        namaMobil.setText("");
        jenisMobil.setText("");
        Tarif.setText("");
        IDmobil.requestFocus();
    }
}
